server:
  port: 8081

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/usuarios
    username: root
    password: Attagama8

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  data:
    mongodb:
      uri: mongodb://localhost:27017/MongoDB_RETO_BACK

appDescription: "Pragma Powerup"
appVersion: "1.0.0"

jwt:
  secret: 9xnmo3kJsDI6GqR1-sk9ufh4rjvyVwSdwu0f8MaF50I